import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabase/server";
import {
  getUserBySupabaseId,
  createChatMessage,
  deductTokens,
} from "@wacke/db";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SACRE_COST = 10;

/**
 * POST /api/chat/sacre
 * Deducts 10 tokens and inserts a generated sacre message into the stream chat.
 */
export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return NextResponse.json({ error: "Non autorisé" }, { status: 401 });
    }

    const token = authHeader.replace(/^Bearer\s+/i, "").trim();

    // Robust auth extraction: support mock-session (Kick/demo), real JWTs, and fallbacks
    let authUserId: string | null = null;

    if (token.startsWith("mock-session:")) {
      const parts = token.split(":");
      authUserId = parts.length >= 3 ? parts.slice(2).join(":") : null;
    } else if (token.includes(".")) {
      try {
        const payloadB64 = token.split(".")[1];
        const payload = JSON.parse(Buffer.from(payloadB64, "base64").toString("utf8"));
        authUserId = payload.sub || payload.user_id || payload.id || null;
      } catch {}
    }

    if (!authUserId) {
      try {
        const supabase = getSupabaseAdmin();
        const {
          data: { user: authUser },
          error: authError,
        } = await supabase.auth.getUser(token);

        if (!authError && authUser) {
          authUserId = authUser.id;
        }
      } catch {}
    }

    if (!authUserId) {
      return NextResponse.json({ error: "Session invalide" }, { status: 401 });
    }

    const { prefix, core, suffix, streamId } = await req.json();

    if (!prefix || !core || !suffix || !streamId) {
      return NextResponse.json(
        { error: "Paramètres de sacre manquants" },
        { status: 400 }
      );
    }

    const user = await getUserBySupabaseId(authUserId);
    if (!user) {
      return NextResponse.json({ error: "Utilisateur introuvable" }, { status: 404 });
    }

    const content = `${prefix} ${core} ${suffix}! 🤬`;

    // Check if streamId is a valid UUID
    const isValidStreamId = streamId && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(streamId);

    // 1. Deduct tokens
    try {
      await deductTokens({
        userId: user.id,
        amount: SACRE_COST,
        reason: `Sacre généré: ${core}`,
        streamId: isValidStreamId ? streamId : undefined,
      });
    } catch (err: any) {
      return NextResponse.json(
        { error: err.message || "Fonds insuffisants" },
        { status: 402 }
      );
    }

    // 2. Create chat message
    let message;
    if (isValidStreamId) {
      message = await createChatMessage({
        streamId,
        userId: user.id,
        content,
        isSacre: true, // Swears generated bypass normal filter since they are authentic
      });
    } else {
      message = {
        id: `mock-msg-${Date.now()}`,
        streamId,
        userId: user.id,
        content,
        isSacre: true,
        isDeleted: false,
        createdAt: new Date(),
      };
    }

    return NextResponse.json({ success: true, message });
  } catch (error) {
    console.error("[sacre API error]", error);
    return NextResponse.json({ error: "Erreur serveur" }, { status: 500 });
  }
}
