import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabase/server";
import {
  getUserBySupabaseId,
  createChatMessage,
  deductTokens,
} from "@wacke/db";

export const runtime = "nodejs";

const SACRE_COST = 10;

/**
 * POST /api/chat/sacre
 * Deducts 10 tokens and inserts a generated sacre message into the stream chat.
 */
export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return NextResponse.json({ error: "Non autorisé" }, { status: 401 });
    }

    const token = authHeader.replace("Bearer ", "");
    const supabase = getSupabaseAdmin();
    const {
      data: { user: authUser },
      error: authError,
    } = await supabase.auth.getUser(token);

    if (authError || !authUser) {
      return NextResponse.json({ error: "Session invalide" }, { status: 401 });
    }

    const { prefix, core, suffix, streamId } = await req.json();

    if (!prefix || !core || !suffix || !streamId) {
      return NextResponse.json(
        { error: "Paramètres de sacre manquants" },
        { status: 400 }
      );
    }

    const user = await getUserBySupabaseId(authUser.id);
    if (!user) {
      return NextResponse.json({ error: "Utilisateur introuvable" }, { status: 404 });
    }

    const content = `${prefix} ${core} ${suffix}! 🤬`;

    // 1. Deduct tokens (10 tokens for generation)
    try {
      await deductTokens({
        userId: user.id,
        amount: SACRE_COST,
        reason: `Sacre généré: ${core}`,
        streamId,
      });
    } catch (err: any) {
      return NextResponse.json(
        { error: err.message || "Fonds insuffisants" },
        { status: 402 }
      );
    }

    // 2. Create chat message
    const message = await createChatMessage({
      streamId,
      userId: user.id,
      content,
      isSacre: true, // Swears generated bypass normal filter since they are authentic
    });

    return NextResponse.json({ success: true, message });
  } catch (error) {
    console.error("[sacre API error]", error);
    return NextResponse.json({ error: "Erreur serveur" }, { status: 500 });
  }
}
